services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    environment:
      - REDIS_URL=redis://redis:6379 
    depends_on:
      - mongo
      - redis
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    restart: always

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  mongo_data:
